# Generated by Django 5.1.3 on 2025-10-08 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Run_Cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre_Cliente', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo', models.TextField()),
                ('Telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Detalle', models.TextField()),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Nombre_Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascotas')),
                ('Run_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
